/**
 * The mark, as a program.
 *
 * A P set on the same grid of squircle tiles as the product shelf on the home
 * page. Every shipped thing is a filled tile; one slot is open, in blue, for
 * the next one. The open slot sits where the bowl closes back to the stem: the
 * last piece.
 *
 * Two cuts, because a grid mark cannot simply be scaled down:
 *   display  40px and up. Squircle tiles, the open slot as an outline.
 *   small    16 to 24px. Drawn on a real 16x16 pixel grid, 2px tiles and 1px
 *            gaps on whole pixels so every gap stays open. A 2px square cannot
 *            carry an outline, so here the open slot is a filled blue pixel.
 *
 * Run `node scripts/mark.mjs` to regenerate every file below. PNG and ICO
 * exports are rasterized from these SVGs; see the colophon.
 */
import { writeFileSync } from "node:fs";

const NAVY = "#0F1B33";
const PAPER = "#FBFBFA";
const BLUE = "#2F6BFF";
const f = (v) => +v.toFixed(2);

/** Superellipse |x|^n + |y|^n = 1, sampled and joined with Catmull-Rom. */
function squircle(n, steps, cx, cy, rx, ry) {
  const p = [];
  for (let i = 0; i < steps; i++) {
    const t = (i / steps) * 2 * Math.PI;
    const c = Math.cos(t);
    const s = Math.sin(t);
    p.push([
      cx + Math.sign(c) * Math.abs(c) ** (2 / n) * rx,
      cy + Math.sign(s) * Math.abs(s) ** (2 / n) * ry,
    ]);
  }
  const L = p.length;
  let d = `M${f(p[0][0])},${f(p[0][1])}`;
  for (let i = 0; i < L; i++) {
    const a = p[(i - 1 + L) % L], b = p[i], c = p[(i + 1) % L], e = p[(i + 2) % L];
    d +=
      `C${f(b[0] + (c[0] - a[0]) / 6)},${f(b[1] + (c[1] - a[1]) / 6)}` +
      ` ${f(c[0] - (e[0] - b[0]) / 6)},${f(c[1] - (e[1] - b[1]) / 6)}` +
      ` ${f(c[0])},${f(c[1])}`;
  }
  return `${d}Z`;
}

/** The letter, as data. X: shipped. O: the open slot. .: empty. */
const GRID = ["XXX", "X.X", "XXO", "X..", "X.."];

function display() {
  const pitch = 8.7;
  const tile = 7.35;
  const w = 3 * pitch - (pitch - tile);
  const h = 5 * pitch - (pitch - tile);
  // A P carries its weight on the left, so it sits a hair right of centre.
  const ox = 32 - w / 2 + 0.9;
  const oy = 32 - h / 2;
  let body = "";
  GRID.forEach((row, r) =>
    [...row].forEach((ch, c) => {
      const cx = ox + c * pitch + tile / 2;
      const cy = oy + r * pitch + tile / 2;
      if (ch === "X")
        body += `<path d="${squircle(4.5, 24, cx, cy, tile / 2, tile / 2)}" fill="${PAPER}"/>`;
      if (ch === "O")
        body += `<path d="${squircle(4.5, 24, cx, cy, tile / 2 - 0.85, tile / 2 - 0.85)}" fill="none" stroke="${BLUE}" stroke-width="1.7"/>`;
    })
  );
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64" role="img" aria-label="Parth Madhvani"><path d="${squircle(4.5, 40, 32, 32, 32, 32)}" fill="${NAVY}"/>${body}</svg>`;
}

function small() {
  let body = "";
  GRID.forEach((row, r) =>
    [...row].forEach((ch, c) => {
      const x = 4 + c * 3;
      const y = 1 + r * 3;
      if (ch === "X") body += `<rect x="${x}" y="${y}" width="2" height="2" fill="${PAPER}"/>`;
      if (ch === "O") body += `<rect x="${x}" y="${y}" width="2" height="2" fill="${BLUE}"/>`;
    })
  );
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16 16" width="16" height="16" shape-rendering="crispEdges" role="img" aria-label="Parth Madhvani"><rect width="16" height="16" rx="3.5" fill="${NAVY}" shape-rendering="geometricPrecision"/>${body}</svg>`;
}

const D = display();
const S = small();

writeFileSync("public/media/mark.svg", D);
writeFileSync("public/media/mark-small.svg", S);
writeFileSync("app/icon.svg", S);
// Bundled as a string so OG cards never read public/ at runtime: a dynamic
// OG route on Vercel is not guaranteed to have public/ in its function.
writeFileSync(
  "lib/mark-svg.ts",
  `// Generated by scripts/mark.mjs. Do not edit by hand.\nexport const MARK_SVG = ${JSON.stringify(D)};\n`
);

console.log(`display ${D.length}b · small ${S.length}b · 4 files written`);
